### ISSUE TITLE
Remap <esc> to <jk> in init.vim but not working

### ISSUE THREAD

**Issue by jackaccyou** [lunixbochs/ActualVim#108]
I remap <esc> to <jk> in the init.vim, but when i press <jk> in sublime text 3 when it's insert mode, the bar at the bottom still shows "insert mode". However, "jk" is not typed on the file.

**Comment by lunixbochs** [comment]
see https://github.com/lunixbochs/ActualVim/issues/97#issuecomment-308485117

maybe I'll do this tonight! looks like lots of interest.

**Comment by lunixbochs** [comment]
insert mode remappings are fixed by [0.9.11](https://github.com/lunixbochs/ActualVim/releases/tag/0.9.11)

give package control a bit of time to sync tags (wait for https://packagecontrol.io/packages/ActualVim to read 0.9.11)

**Comment by jackaccyou** [comment]
I have just reinstall ActualVim, i think its 0.9.11. The problem still persist.
#97 Can you explain a little more about "removing the insert heuristics and merging the async branch"? thx

**Comment by lunixbochs** [comment]
Post your mapping in init.vim and full reproduction steps.

**Comment by jackaccyou** [comment]
I am sorry, it indeed works. The problem is that i was using "vintage mode" in sublime before using Actual Vim, I change the key mapping inside the sublime and causes some problem. I comment those out and now its working like a charm:)

**Comment by ldebruyn** [comment]
This resolved my issue as well. Thank you!

**Comment by jackaccyou** [comment]
The remapping doesn't work in visual mode. I can't jump to insert mode from visual mode by "jk"

**Comment by lunixbochs** [comment]
Paste your init.vim. The command I pasted was imap, which I think is just insert mode.

**Comment by jackaccyou** [comment]
` On Jun 23, 2017, at 2:18 AM, jackaccyou ***@***.***> wrote:

 The remapping doesn't work in visual mode. I can't jump to insert mode from visual mode by "jk"

 —
 You are receiving this because you modified the open/close state.
 Reply to this email directly, view it on GitHub, or mute the thread.
`

Yes that's the problem, added vmap now, it works
